apiVersion: v1
kind: Pod
metadata: 
  name: config-pod

spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: COURSE
          valueFrom:
            configMapKeyRef:
              name: config-course
              key: COURSE

        - name: TRAINER
          valueFrom:
            configMapKeyRef:
              name: course-config
              key: TRAINER